
modLoader="javafml" #mandatory

loaderVersion="[31,)" #mandatory

#issueTrackerURL="http://my.issue.tracker/" #optional

[[mods]] #mandatory
modId="expanded_combat" #mandatory
version="1.0.1" #mandatory
displayName="Expanded Combat" #mandatory
#displayURL="http://example.com/" #optional
#logoFile="examplemod.png" #optional
authors="Userofbricks" #optional
# The description text for the mod (multi line!) (#mandatory)
description='''
An Expansion of Minecraft's combat equipment which includes a reimagining of dinnerbone's quiver.
'''

[[dependencies.examplemod]] #optional
    modId="forge" #mandatory
    mandatory=true #mandatory
    versionRange="[31.2.45,)" #mandatory
    ordering="NONE"
    side="BOTH"

[[dependencies.examplemod]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.15.2]"
    ordering="NONE"
    side="BOTH"