
modLoader="javafml" #mandatory

loaderVersion="[37,)" #mandatory

license="All rights reserved"

#issueTrackerURL="http://my.issue.tracker/" #optional

[[mods]] #mandatory
modId="expanded_combat" #mandatory
version="2.3.1-beta_0" #mandatory
displayName="Expanded Combat" #mandatory
#displayURL="http://example.com/" #optional
#logoFile="examplemod.png" #optional
authors="Userofbricks" #optional
# The description text for the mod (multi line!) (#mandatory)
description='''
An Expansion of Minecraft's combat equipment which includes a reimagining of dinnerbone's quiver.
'''

[[dependencies.expanded_combat]] #optional
    modId="forge" #mandatory
    mandatory=true #mandatory
    versionRange="[37,)" #mandatory
    ordering="NONE"
    side="BOTH"

[[dependencies.expanded_combat]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.17.1,1.18)"
    ordering="NONE"
    side="BOTH"

[[dependencies.expanded_combat]]
    modId="curios"
    mandatory=true
    versionRange="[1.17.1-5.0.0.0, )"
    ordering="NONE"
    side="BOTH"