
modLoader="javafml" #mandatory

loaderVersion="${loader_version_range}" #mandatory

license="${mod_license}"

#issueTrackerURL="http://my.issue.tracker/" #optional

[[mods]] #mandatory
modId="${modid}" #mandatory
version="${mod_version}" #mandatory
displayName="${mod_name}" #mandatory
#displayURL="http://example.com/" #optional
#logoFile="examplemod.png" #optional
authors="${mod_authors}" #optional
# The description text for the mod (multi line!) (#mandatory)
description='''${mod_description}'''

[[dependencies.${mod_id}]] #optional
    modId="forge" #mandatory
    mandatory=true #mandatory
    versionRange="${forge_version_range}" #mandatory
    ordering="NONE"
    side="BOTH"

[[dependencies.${mod_id}]]
    modId="minecraft"
    mandatory=true
    versionRange="${minecraft_version_range}"
    ordering="NONE"
    side="BOTH"

[[dependencies.${mod_id}]]
    modId="curios"
    mandatory=true
    versionRange="[${curios_version},)"
    ordering="NONE"
    side="BOTH"

[[dependencies.${mod_id}]]
    modId="cloth_config"
    mandatory=true
    versionRange="[${cloth_config_api_version},)"
    ordering="NONE"
    side="BOTH"

[[dependencies.${mod_id}]]
    modId="twilightforest"
    mandatory=false
    versionRange="[${twilight_forest_version},)"
    ordering="BEFORE"
    side="BOTH"

[[dependencies.${mod_id}]]
    modId="bettercombat"
    mandatory=false
    versionRange="[${better_combat_version},)"
    ordering="AFTER"
    side="BOTH"